version: '3.8'

services:
  dnd-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dnd-service
    ports:
      - "9191:9190"  # Используем порт 9191 на хосте, 9190 в контейнере
    environment:
      - PORT=9190
    restart: unless-stopped


